[phases.build]
cmd = "npm install && npm run build --workspace=metadata-kit && npm run build --workspace=everservice"

[phases.start]
cmd = "cd everservice && npm start"

[variables]
NODE_ENV = "production"