# Cloudflare Pages configuration for Evermark Protocol webapp

name = "evermark-protocol"
compatibility_date = "2024-11-01"

[build]
command = "npm install && npm run build"
cwd = "."

[[pages_build_output_dir]]
directory = ".next"

[env.production]
NODE_ENV = "production"

[env.preview] 
NODE_ENV = "preview"